//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecpay.EInvoice.Integration.Resource {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiUrl_Stage_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiUrl_Stage_Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecpay.EInvoice.Integration.Resource.ApiUrl.Stage.Resource", typeof(ApiUrl_Stage_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Invoice/Allowance 的當地語系化字串。
        /// </summary>
        internal static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Invoice/AllowanceByCollegiate 的當地語系化字串。
        /// </summary>
        internal static string AllowanceByCollegiate {
            get {
                return ResourceManager.GetString("AllowanceByCollegiate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Invoice/AllowanceInvalid 的當地語系化字串。
        /// </summary>
        internal static string AllowanceInvalid {
            get {
                return ResourceManager.GetString("AllowanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Query/CheckLoveCode 的當地語系化字串。
        /// </summary>
        internal static string CheckLoveCode {
            get {
                return ResourceManager.GetString("CheckLoveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Query/CheckMobileBarCode 的當地語系化字串。
        /// </summary>
        internal static string CheckMobileBarCode {
            get {
                return ResourceManager.GetString("CheckMobileBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Invoice/Issue 的當地語系化字串。
        /// </summary>
        internal static string InvoiceCreate {
            get {
                return ResourceManager.GetString("InvoiceCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Invoice/DelayIssue 的當地語系化字串。
        /// </summary>
        internal static string InvoiceDelay {
            get {
                return ResourceManager.GetString("InvoiceDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Invoice/IssueInvalid 的當地語系化字串。
        /// </summary>
        internal static string InvoiceInvalid {
            get {
                return ResourceManager.GetString("InvoiceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Invoice/TriggerIssue 的當地語系化字串。
        /// </summary>
        internal static string InvoiceTrigger {
            get {
                return ResourceManager.GetString("InvoiceTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Notify/InvoiceNotify 的當地語系化字串。
        /// </summary>
        internal static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Query/Allowance 的當地語系化字串。
        /// </summary>
        internal static string QueryAllowance {
            get {
                return ResourceManager.GetString("QueryAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Query/AllowanceInvalid 的當地語系化字串。
        /// </summary>
        internal static string QueryAllowanceInvalid {
            get {
                return ResourceManager.GetString("QueryAllowanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Query/Issue 的當地語系化字串。
        /// </summary>
        internal static string QueryInvoice {
            get {
                return ResourceManager.GetString("QueryInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://einvoice-stage.ecpay.com.tw/Query/IssueInvalid 的當地語系化字串。
        /// </summary>
        internal static string QueryInvoiceInvalid {
            get {
                return ResourceManager.GetString("QueryInvoiceInvalid", resourceCulture);
            }
        }
    }
}
